h_p<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE)
h_p$DateTime<-paste(h_p$Date,h_p$Time, sep=' ')
h_p$DateTime<- strptime(h_p$DateTime, format="%d/%m/%Y %H:%M:%S", tz="")
h_p$Date<-as.Date(h_p$Date,format = "%d/%m/%Y")
h_p<-h_p[(h_p$Date<="2007-02-02")&(h_p$Date>="2007-02-01"),]
png('plot3.png')
plot(h_p$DateTime,h_p$Sub_metering_1, ylab="Energy sub metering", xlab="", type="l", col="black")
lines(h_p$DateTime, h_p$Sub_metering_2, type="l", col="red")
lines(h_p$DateTime, h_p$Sub_metering_3, type="l", col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.8, col=c("black","red","blue"), lty=1)
dev.off()
